version: '3'

tasks:
  start:
    cmds:
      - docker compose up --detach

  stop:
    cmds:
      - docker compose down

  restart:
    cmds:
      - task: stop
      - task: start

  rebuild:
    cmds:
      - docker compose up --detach --build

  logs-server:
    cmds:
      - docker compose logs --follow node-server

  logs-client:
    cmds:
      - docker compose logs --follow node-client

  install-client:
    cmds:
      - docker compose exec -it node-client npm install

  install-server:
    cmds:
      - docker compose exec -it node-server npm install

  create-migration:
    cmds:
      - docker compose exec -it node-server node node_modules/db-migrate/bin/db-migrate create {{.CLI_ARGS}} --sql-file

  migrate-up:
    cmds:
      - docker compose exec -it node-server node node_modules/db-migrate/bin/db-migrate up
